version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-location-app
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: locations
            MYSQL_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
            - 3306:3306
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
